// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAz7811C3-xPE-CWsJZM0HVba6kUqdUT0',
    appId: '1:743665484397:web:12f5580e6098751ee6f564',
    messagingSenderId: '743665484397',
    projectId: 'dukan-sathi-601a1',
    authDomain: 'dukan-sathi-601a1.firebaseapp.com',
    storageBucket: 'dukan-sathi-601a1.firebasestorage.app',
    measurementId: 'G-X8XMXVLHPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2RtIKQ16psAuaJN1M9xv8ER8JtrmBEE',
    appId: '1:743665484397:android:c328c69e68f6ea0de6f564',
    messagingSenderId: '743665484397',
    projectId: 'dukan-sathi-601a1',
    storageBucket: 'dukan-sathi-601a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Bf7sdp8GfiClapbSt6XdGWs-fHmLZ4k',
    appId: '1:743665484397:ios:2760a8541c94a8d6e6f564',
    messagingSenderId: '743665484397',
    projectId: 'dukan-sathi-601a1',
    storageBucket: 'dukan-sathi-601a1.firebasestorage.app',
    iosBundleId: 'com.example.dukanSathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Bf7sdp8GfiClapbSt6XdGWs-fHmLZ4k',
    appId: '1:743665484397:ios:2760a8541c94a8d6e6f564',
    messagingSenderId: '743665484397',
    projectId: 'dukan-sathi-601a1',
    storageBucket: 'dukan-sathi-601a1.firebasestorage.app',
    iosBundleId: 'com.example.dukanSathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAz7811C3-xPE-CWsJZM0HVba6kUqdUT0',
    appId: '1:743665484397:web:27fa75d3b06cd8d6e6f564',
    messagingSenderId: '743665484397',
    projectId: 'dukan-sathi-601a1',
    authDomain: 'dukan-sathi-601a1.firebaseapp.com',
    storageBucket: 'dukan-sathi-601a1.firebasestorage.app',
    measurementId: 'G-F16RZXF175',
  );
}
