import 'package:dukan_sathi/auth_gate.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart'; // Import FirebaseAuth
import 'package:provider/provider.dart'; // Import Provider
import 'firebase_options.dart'; // This file was generated by flutterfire configure
import 'package:get/get_navigation/get_navigation.dart';

void main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // We wrap our entire app in MultiProvider
  runApp(
    MultiProvider(
      providers: [
        // This provider makes the user's auth state (User or null)
        // available to the entire app via widgets like AuthGate.
        StreamProvider<User?>(
          create: (_) => FirebaseAuth.instance.authStateChanges(),
          initialData: null,
        ),
      ],
      child: const MainApp(),
    ),
  );
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    //using a SafeArea To Remov e the debug banner
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      // The home is now our AuthGate, which will decide which
      // page to show (Onboarding or the RoleRouter)
      home: AuthGate(),
    );
  }
}
